name: Omkaar

description: Mathematics & Python Enthusiast

avatar: https://avatars.githubusercontent.com/u/79257339

footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github: Infiniticity
  instagram:
  linkedin: omkaar-nerurkar
  pinterest: infiniticity
  rss:
  twitter:
  stackoverflow: 15069079
  youtube:
  quora: Infiniticity
  discord: 703134690613264425


disqus:

google_analytics:

favicon: "https://raw.githubusercontent.com/Infiniticity/Infiniticity.github.io/dev/assets/images/favicon.ico"

url: https://infiniticity.github.io

baseurl: ""

permalink: /:title/

version: v1.2.0

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

sass:
  style: :expanded

gems:
  - jekyll-sitemap
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
